### ISSUE TITLE
Version Controlling

### ISSUE THREAD

**Issue by bemcdonnell** [OpenWaterAnalytics/swmm-nrtestsuite#2]
@michaeltryby, just a thought - how do you feel about tagging the benchmarks with the same version number as the SWMM benchmark that is released?

Like the latest would be `5.1.13` instead of `1.0.1`.

**Comment by michaeltryby** [comment]
@bemcdonnell Having everything the same number makes things confusing. Image everything is numbered the same, you say "v5.1.13" do you mean source code, build, or example version? Then to keep everything the same when you bump versions you have to bump everything ... pretty soon the version number loses its meaning.
